module Texts where

wakeUp = "You open you eyes just to find yourself lying down on a pink pillow "
    ++ "in a\nslightly lit up room. Right above you is the last thing you could"
    ++ " remember:\nA large metal pipe. After standing up and trying to avoid "
    ++ "that pipe you noticed\nthat a small voice message device has fallen off"
    ++ " you.               :? for help"

help = "Help page:"
    ++ "\n :help (:?, :h)                                    -- show help page"
    ++ "\n :save (:s)                                        -- save game"
    ++ "\n :quit, :exit (:q, :e)                             -- quit game"
    ++ "\n go [north, east, south, west] (n, e, s, w)        -- move around"
    ++ "\n go [up, down] (u, d)                              -- use elevator"
    ++ "\n jump down (j)                                     -- jump through holes"
    ++ "\n look around (l)                                   -- inspect your environment"
    ++ "\n examine (x)                                       -- examine yourself"
    ++ "\n take {Item}                                       -- take item"
    ++ "\n drop {Item}                                       -- drop item"
    ++ "\n push {Object}                                     -- push an object"
    ++ "\n open {Object}                                     -- open an object"
    ++ "\n use {Item}                                        -- use item"
    ++ "\n put {Item} in {Object}                            -- interact"

pushedShelf = "You pushed the shelf out of the way revealing a small hole leading to the a\ndark room below you."

rigthLockerCode = "The lockers display shows you the words \"Right Code\" before opening and\nletting something fall out of it."

tRoomDoorOpen = "Access granted. Transmission Room door opened."

gameWon = "You inserted the Long Field Communication Module into the "
    ++ "transmission tower\nallowing it to power up the right way. You type in "
    ++ "the transmission code to\ncontact the F.T.S. and to tell them what "
    ++ "happened.\n\nImmedietly after you send the message you recieved a "
    ++ "notification from the federation telling you that they are going to "
    ++ "pick you up and end this horror trip of yours.\n\n You won. Press enter."

gameOver = ""
    ++ "Directly after jumping into the hole you      \\                  /\n"
    ++ "realise that sign on floor zero      _________))                ((_________\n"
    ++ "stating that there is a snakemoth   /.-------./\\\\    \\    /    //\\.-------.\\\n"
    ++ "breeding room behind a blocked     //#######//##\\\\   ))  ((   //##\\\\#######\\\\\n"
    ++ "door. But before you could think  //#######//###((  ((    ))  ))###\\\\#######\\\\\n"
    ++ "of doing something a hungry and  ((#######((#####\\\\  \\\\  //  //#####))#######))\n"
    ++ "giant snakemoth attacks you. You  \\##' '###\\######\\\\  \\)(/  //######/###' '##/\n"
    ++ "try to evade her attack by         )'    ''#)'  '##\\'->oo<-'/##'  '(#''    '(\n"
    ++ "jumping to the side.                       (       ''\\'..'/''       )\n"
    ++ "                                                      \\\"\"(\n"
    ++ "Successfully avoiding her claws and teeth you          '- )\n"
    ++ "quickly realise that the F.T.S. packed more than a     / /\n"
    ++ "dozent of snakemoths in here. Accepting your fate     ( /\\\n"
    ++ "you sit down and close your eyes before screaming     /\\| \\\n"
    ++ "up one more time!                                    (  \\\n"
    ++ "                                                         )\n"
    ++ "        ________                          ________      /             \n"
    ++ "       /  _____/_____    _____   ____     \\_____  \\___ (__ ___________ \n"
    ++ "      /   \\  ___\\__  \\  /     \\_/ __ \\     /   |   \\  \\/ // __ \\_  __ \\\n"
    ++ "      \\    \\_\\  \\/ __ \\|  Y Y  \\  ___/    /    |    \\   /\\  ___/|  | \\/\n"
    ++ "       \\______  (____  /__|_|  /\\___  >   \\_______  /\\_/  \\___  >__|   \n"
    ++ "              \\/     \\/      \\/     \\/            \\/          \\/     \n"

enteringCave = "Without fear you venture off into the depths of the cave.\n"
    ++ "After turning left and now facing north you have gotten yourself into a"
    ++ "room-ish like cavern with three branches."

foundDeadBody = "On the ground you find one seperated arm. Your feeling tells you that you are\n"
    ++ "not alone here and that you should go back the ship immediately. But first you\n"
    ++ "inspect the arm. Due to the small tattoos on the hand you quickly realise that\n"
    ++ "this is the arm of your former engineering supervisor Alan Rickman.\n"
    ++ "Upon closer inspection you see the code \"4546B\" written on it."

locName r
    | r ==  1 = "Level 0 - Floor"
    | r ==  2 = "Level 0 - Elevator Room"
    | r ==  3 = "Level 0 - Chiefs Room"
    | r ==  4 = "Level 0 - Machine Room"
    | r ==  5 = "Level 0 - Snake Farm"
    | r ==  6 = "Level 0 - Terminal Room"
    | r ==  7 = "Level 0 - Laboratory"
    | r ==  8 = "Level 0 - Western Panorama Room"
    | r ==  9 = "Level 0 - Preperation Room"
    | r == 10 = "Level 0 - Airlock Room"
    | r == 11 = "Level 1 - Elevator Room"
    | r == 12 = "Level 1 - Eastern Panorama Room"
    | r == 13 = "Level 1 - Northern Floor"
    | r == 14 = "Level 1 - Southern Floor"
    | r == 15 = "Level 1 - Incubation Room"
    | r == 16 = "Level 1 - Stock"
    | r == 17 = "Level 1 - Eastern Floor"
    | r == 18 = "Level 2 - Elevator Room"
    | r == 19 = "Level 2 - Transmission Room"
    | otherwise = "Error"

locText r
    | r ==  1 = "Text for: Level 0 - Floor: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r ==  2 = "Text for: Level 0 - Elevator Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r ==  3 = "Text for: Level 0 - Chiefs Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r ==  4 = "Text for: Level 0 - Machine Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r ==  5 = "Text for: Level 0 - Snake Farm: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam etYOU ARE DEAD PRESS ENTER"
    | r ==  6 = "Text for: Level 0 - Terminal Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r ==  7 = "Text for: Level 0 - Laboratory: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r ==  8 = "Text for: Level 0 - Western Panorama Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r ==  9 = "Text for: Level 0 - Preperation Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 10 = "Text for: Level 0 - Airlock Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 11 = "Text for: Level 1 - Elevator Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 12 = "Text for: Level 1 - Eastern Panorama Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 13 = "Text for: Level 1 - Northern Floor: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 14 = "Text for: Level 1 - Southern Floor: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 15 = "Text for: Level 1 - Incubation Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 16 = "Text for: Level 1 - Stock: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 17 = "Text for: Level 1 - Eastern Floor: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 18 = "Text for: Level 2 - Elevator Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | r == 19 = "Text for: Level 2 - Transmission Room: Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et"
    | otherwise = "Error"

itemName i
    | i == 0 = "Chiefs ID"
    | i == 1 = "Long Field Communication Module (LFCM)"
    | i == 2 = "Universal Compression Unit (UCU)"
    | i == 3 = "Voice Message"
    | otherwise = "Error"

itemText i
    | i == 0 = "Chiefs ID TEXT"
    | i == 1 = "Long Field Communication Module (LFCM) TEXT"
    | i == 2 = "Universal Compression Unit (UCU) TEXT"
    | i == 3 = "\"HELLO HO\""
    | otherwise = "Error"
