module Texts where

wakeUp = "You wake up in a dark room."

showR r
    | r ==  1 = "Level 0 - Floor"
    | r ==  2 = "Level 0 - Elevator Room"
    | r ==  3 = "Level 0 - Chiefs Room"
    | r ==  4 = "Level 0 - Machine Room"
    | r ==  5 = "Level 0 - Snake Farm"
    | r ==  6 = "Level 0 - Terminal Room"
    | r ==  7 = "Level 0 - Laboratory"
    | r ==  8 = "Level 0 - Western Panorama Room"
    | r ==  9 = "Level 0 - Preperation Room"
    | r == 10 = "Level 0 - Airlock Room"
    | r == 11 = "Level 1 - Elevator Room"
    | r == 12 = "Level 1 - Eastern Panorama Room"
    | r == 13 = "Level 1 - Northern Floor"
    | r == 14 = "Level 1 - Southern Floor"
    | r == 15 = "Level 1 - Incubation Room"
    | r == 16 = "Level 1 - Stock"
    | r == 17 = "Level 1 - Eastern Floor"
    | r == 18 = "Level 2 - Elevator Room"
    | r == 19 = "Level 2 - Transmission Room"
    | otherwise = "Error"

printT r
    | r ==  1 = "Level 0 - Floor"
    | r ==  2 = "Level 0 - Elevator Room"
    | r ==  3 = "Level 0 - Chiefs Room"
    | r ==  4 = "Level 0 - Machine Room"
    | r ==  5 = "Level 0 - Snake Farm"
    | r ==  6 = "Level 0 - Terminal Room"
    | r ==  7 = "Level 0 - Laboratory"
    | r ==  8 = "Level 0 - Western Panorama Room"
    | r ==  9 = "Level 0 - Preperation Room"
    | r == 10 = "Level 0 - Airlock Room"
    | r == 11 = "Level 1 - Elevator Room"
    | r == 12 = "Level 1 - Eastern Panorama Room"
    | r == 13 = "Level 1 - Northern Floor"
    | r == 14 = "Level 1 - Southern Floor"
    | r == 15 = "Level 1 - Incubation Room"
    | r == 16 = "Level 1 - Stock"
    | r == 17 = "Level 1 - Eastern Floor"
    | r == 18 = "Level 2 - Elevator Room"
    | r == 19 = "Level 2 - Transmission Room"
    | otherwise = "Error"
