module Texts where

wakeUp = "You open your eyes just to find yourself lying down on a pink pillow "
    ++ "in a\nslightly lit up room. Right above you is the last thing you could"
    ++ " remember:\nA large metal pipe. After standing up and trying to avoid "
    ++ "that pipe you noticed\nthat a small voice message device has fallen off"
    ++ " you.               :? for help"

help = "Help page:\n"
    ++ "\n :help (:?, :h) ..................................... show help page"
    ++ "\n :save (:s) ......................................... save game"
    ++ "\n :quit, :exit (:q, :e) .............................. quit game"
    ++ "\n go [north, east, south, west] (n, e, s, w) ......... move around"
    ++ "\n go [up, down] (u, d) ............................... use elevator"
    ++ "\n jump down (j) ...................................... jump through holes"
    ++ "\n look around (l) .................................... inspect your environment"
    ++ "\n examine (x) ........................................ examine yourself"
    ++ "\n take {Item} ........................................ take item"
    ++ "\n drop {Item} ........................................ drop item"
    ++ "\n inspect {Item} ..................................... inspect/ use item"
    ++ "\n use {Object} ....................................... use an object"
    ++ "\n push {Object} ...................................... push an object"
    ++ "\n open {Object} ...................................... open an object"
    ++ "\n put {Item} in {Object} ............................. interact"

pushedShelf = "You pushed the shelf out of the way revealing a small hole leading to the a\ndark room below you."

rigthLockerCode = "The lockers display shows you the words \"Right Code\" before opening\nits door. A small fabricator activates itself creating a long field\ncommunication module. After finishing it sprays sparks\nfollowed by dropping the LFCM."

tRoomDoorOpen = "Access granted. Transmission Room door opened."

enteringCrafting = "-- Fabricator opening in emergency mode.\n-- Restoring corrupted Data.\n-- Error 43_0B: Some files cannot be restored.\n"
craftable = "Available recipes:\n\n    [1] Craft Plasma Sword\n            needs: 2 scrap metal\n                                                  [Enter] Leave Fabricator\n    [2] Craft Stun Gun\n            needs: 5 scrap metal\n                                                  [I] Show Inventory\n    [3] Craft Air Condensator\n            needs: 1 UCU, 3 scrap metal\n\n    [4] Caft Analysis Ball\n            needs: 1 UCU, 7 scrap metal\n\n    [5] Craft MediKit\n            needs: 2 scrap metal"

gameWon = "You inserted the Long Field Communication Module into the "
    ++ "transmission tower\nallowing it to power up the right way. You type in "
    ++ "the transmission code to\ncontact the F.T.S. and to tell them what "
    ++ "happened.\n\nImmedietly after you send the message you recieved a "
    ++ "notification from the federation telling you that they are going to "
    ++ "pick you up and end this horror trip of yours.\n\n You won. Press enter."

terminalFile file
    | file == "research3.tdoc" = 
        "\n"
        ++ "       ARK-27B Dark-Matter-Cluster by sTech: Test 3a\n"
        ++ " ______________________________________________________________________________\n"
        ++ "                      |\n"
        ++ "                      |  The Dark-Matter-Cluster is a new way of traveling\n"
        ++ "        \\^^^^/        |  through hyperspace. It's more than 62 times faster\n"
        ++ "     \"   |  |   \"     |  then the current system from spaceX.\n"
        ++ "         |  |         |\n"
        ++ "    .-'^^^^^^^^'-.    |  Its use extends over more areas then just traveling,\n"
        ++ "  |_   F. T. S.   _|  |  i.e. communication and weaponry.\n"
        ++ "    '-.  ====  .-'    |\n"
        ++ "    /  \\( == )/  \\    |  The first two tests returned promissing results as\n"
        ++ "    |___ \\  / ___|    |  they surpassed their expectations by a lot.\n"
        ++ "        \\|  |/        |  Of course new tests are imminent and shall be\n"
        ++ "         |  |         |  executed ASAP.\n"
        ++ "     \"   |  |   \"     |\n"
        ++ "         |  |         |  For now the F.T.S. Discovery and the F.T.S. Tantive\n"
        ++ "          \\/          |  will venture out to proceed with test 3a and test 3b\n"
        ++ "        \"    \"        |  in the Argelinn-System and we will hope for the\n"
        ++ "                      |  best that they come back with valuable results.\n"
        ++ " Terran-Document      |\n"
        ++ " Reader v3.14         |                     - sTech CEO Holro Garill\n\n"
    | file == "alsiem-tribute.tdoc" = 
        "\n"
        ++ "      Aurelius Ly Siem - Engineer, politician, fleet commander\n"
        ++ " ______________________________________________________________________________\n"
        ++ "                      |\n"
        ++ "                      |  A tribute to Aurelius Ly Siem.\n"
        ++ "        \\^^^^/        |  From an early age, Aurelius was concerned with the ad-\n"
        ++ "     \"   |  |   \"     |  vancement of mankind. In collaboration with Elon Musk,\n"
        ++ "         |  |         |  he designed the first hyperdrive, which opened the\n"
        ++ "    .-'^^^^^^^^'-.    |  door to the expansion of humanity into the vastness of\n"
        ++ "  |_   F. T. S.   _|  |  space, where years later he would make first contact\n"
        ++ "    '-.  ====  .-'    |  with the Novans. Prior to the great expansion phase,\n"
        ++ "    /  \\( == )/  \\    |  Aurelius became involved with politics, helping with\n"
        ++ "    |___ \\  / ___|    |  globalization, held the office of the first grand\n"
        ++ "        \\|  |/        |  chancellor of the USE and later sat on the Council of\n"
        ++ "         |  |         |  the United Earth Alliance. Here his criticism of their\n"
        ++ "     \"   |  |   \"     |  politics with the Novan Empire would later cost him\n"
        ++ "         |  |         |  his seat. But even after the outbreak of the Orion\n"
        ++ "          \\/          |  War, the first inter planetary war with the Novans, he\n"
        ++ "        \"    \"        |  stopped their invasion with his flagship, the T.D.C.\n"
        ++ "                      |  Eclipse. A month later he lost his life in the unrest\n"
        ++ " Terran-Document      |  that followed among Terran systems. But while he may\n"
        ++ " Reader v3.14         |  be gone, he will always be remenbered.     - Ariana\n\n"
    | file == "militarylaunch.tdoc" = 
        "\n"
        ++ "     The Federation of Terran Systems launches its first imperial war ship.\n"
        ++ " ______________________________________________________________________________\n"
        ++ "                      |\n"
        ++ "                      |  After the riots that existed among the Terran colony\n"
        ++ "        \\^^^^/        |  planets were eliminated by our new president Ariana\n"
        ++ "     \"   |  |   \"     |  Ly Siem, daughter of Aurelius Ly Siem, the newly\n"
        ++ "         |  |         |  founded Federation of Terran Systems is now again\n"
        ++ "    .-'^^^^^^^^'-.    |  focusing on the war with the Novan Empire.\n"
        ++ "  |_   F. T. S.   _|  |\n"
        ++ "    '-.  ====  .-'    |  After the T.D.C. Eclipse was laid down in reaction\n"
        ++ "    /  \\( == )/  \\    |  to the death of Aurelius, it is now sent back to the\n"
        ++ "    |___ \\  / ___|    |  front lines under its new name \'F.T.S. Eclipse\'.\n"
        ++ "        \\|  |/        |  This was decided by a new law of our president.\n"
        ++ "         |  |         |  The law further initiated the dissolution of the old\n"
        ++ "     \"   |  |   \"     |  T.D.C, the Terran Defensive Corps.\n"
        ++ "         |  |         |\n"
        ++ "          \\/          |  Professor Chirpa, the president's head of security,\n"
        ++ "        \"    \"        |  said that the Eclipse's combined fighting power\n"
        ++ "                      |  should quickly put an end to this devastating war.\n"
        ++ " Terran-Document      |\n"
        ++ " Reader v3.14         |                     - BILD reporter Arthur Kayn\n\n"
    | file == "militarylaunch-comment17.tdoc" = 
        "\n"
        ++ "     Comment: Incompetence of a so called \'journalist\'.\n"
        ++ " ______________________________________________________________________________\n"
        ++ "                      |\n"
        ++ "                      |  BILD \'journalist\' Arthur Kayn strikes again!\n"
        ++ "        \\^^^^/        |  I really do not understand, why he is still in this\n"
        ++ "     \"   |  |   \"     |  position.\n"
        ++ "         |  |         |\n"
        ++ "    .-'^^^^^^^^'-.    |  First of all, the T.D.C. Eclipse was not \'laid down\',\n"
        ++ "  |_   F. T. S.   _|  |  it was forcefully taken away from Aurelius by the\n"
        ++ "    '-.  ====  .-'    |  former (right-wing) Grand President Amthor because\n"
        ++ "    /  \\( == )/  \\    |  he did not like that Aurelius saved us from the\n"
        ++ "    |___ \\  / ___|    |  invasion ON HIS OWN!.\n"
        ++ "        \\|  |/        |  One could argue about if one person should have the\n"
        ++ "         |  |         |  complete power over such a huge flagship, sure, but\n"
        ++ "     \"   |  |   \"     |  you don\'t shoot him in the back to take it away!\n"
        ++ "         |  |         |  Then, the ship isn\'t \'sent to the front lines\n"
        ++ "          \\/          |  again\', it got RECAPTURED because Amthor f**ing lost\n"
        ++ "        \"    \"        |  the ship to the Novas!\n"
        ++ "                      |\n"
        ++ " Terran-Document      |  Oh and \'focusing again on the war\' is such a populist\n"
        ++ " Reader v3.14         |  expression... Please lay down your job!\n\n"
    | file == "interview.tdoc" = 
        "\n"
        ++ "          \"The day of the invasion\" with Aurelius Ly Siem.\n"
        ++ " ______________________________________________________________________________\n"
        ++ "                      |\n"
        ++ "                      |  Reporter> I know it may be too soon, but I wanted to\n"
        ++ "        \\^^^^/        |   ask you about the day of the Invasion. What happened?\n"
        ++ "     \"   |  |   \"     |   How was it for you?\n"
        ++ "         |  |         |\n"
        ++ "    .-'^^^^^^^^'-.    |  Aurelius> It was .. devastating. I was still sleeping\n"
        ++ "  |_   F. T. S.   _|  |   at my summer home on earth when the attack happened.\n"
        ++ "    '-.  ====  .-'    |   Leon slammed on my door to wake me up. Obviously, our\n"
        ++ "    /  \\( == )/  \\    |   dear Grand President did not want me to know about it\n"
        ++ "    |___ \\  / ___|    |   and even cut my com\'s. When I looked in the sky I saw\n"
        ++ "        \\|  |/        |   what they did. They attacked Mankind Alpha. Mankind\n"
        ++ "         |  |         |   Alpha! My life work. My child! When the secondary arm\n"
        ++ "     \"   |  |   \"     |   broke down and crashed into earth I quickly ran to my\n"
        ++ "         |  |         |   personal ship. I just had to do something.\n"
        ++ "          \\/          |\n"
        ++ "        \"    \"        |  Reporter> So you started up this secret flagship on\n"
        ++ "                      |   the backside of the moon to massacre their peaple?\n"
        ++ " Terran-Document      |\n"
        ++ " Reader v3.14         |  Aurelius> You know .. I find it just ter[CORRUPTED]\n\n"
    | file == "current-0002.log" = 
        "\n"
        ++ "         Crash log #0002.B - Hyperspace engine complete shutdown fail.         \n"
        ++ "\n"
        ++ " 2095 05 29\n"
        ++ "  [17:56:34] :: Warning at Engine R5   - detected high gravity waves\n"
        ++ "  [17:56:35] :: Error at Engine Root   - gravitational waves at too high ratio\n"
        ++ "  [17:56:42] :: Error at Engine Root   - emergency deactivation at all engines\n"
        ++ "  [17:57:03] :: Error at Shield L2     - detected high energy\n"
        ++ "  [18:00:56] :: Error at Shield Root   - breakdown exception\n"
        ++ "  [18:01:12] :: NoSignal-Error         - Hull L2 missing\n"
        ++ "  [18:02:32] :: NoSignal-Error         - Engine R4 missing\n"
        ++ "  [18:02:33] :: Warning at Engine Root - Jump initiated\n"
        ++ "  [18:02:35] :: NoSignal-Error         - Machine room missing\n"
        ++ "  [18:02:35] :: Notification           - closing all security doors\n"
        ++ "  [18:02:38] :: Warning at Engine Root - Jump started\n"
        ++ "  [18:02:40] :: Error at Engine Root   - Jump failed\n"
        ++ "  [18:02:41] -- Recognized 42780 NoSignal-Errors\n"
        ++ "  [18:04:34] :: Notification           - complete system shutdown\n"
        ++ " 2095 05 30\n"
        ++ "  [01:00:00] :: Notification           - complete system reboot\n"
        ++ "  [01:00:59] -- Lifeformscan returns several cyborg-like-creatures\n"
        ++ "\n\n"
    | file == "logo.txt" = 
        "\n"
        ++ "      \\^^^^/        \n"
        ++ "   \"   |  |   \"     \n"
        ++ "       |  |         \n"
        ++ "  .-'^^^^^^^^'-.    \n"
        ++ "|_   F. T. S.   _|  \n"
        ++ "  '-.  ====  .-'    \n"
        ++ "  /  \\( == )/  \\    \n"
        ++ "  |___ \\  / ___|    \n"
        ++ "      \\|  |/        \n"
        ++ "       |  |         \n"
        ++ "   \"   |  |   \"     \n"
        ++ "       |  |         \n"
        ++ "        \\/          \n"
        ++ "      \"    \"        \n"
    | otherwise = "Error: Opened non-existing file.\n"

gameOverSnake = ""
    ++ "Directly after jumping into the hole you      \\                  /\n"
    ++ "realise that sign on floor zero      _________))                ((_________\n"
    ++ "stating that there is a snakemoth   /.-------./\\\\    \\    /    //\\.-------.\\\n"
    ++ "breeding room behind a blocked     //#######//##\\\\   ))  ((   //##\\\\#######\\\\\n"
    ++ "door. But before you could think  //#######//###((  ((    ))  ))###\\\\#######\\\\\n"
    ++ "of doing something a hungry and  ((#######((#####\\\\  \\\\  //  //#####))#######))\n"
    ++ "giant snakemoth attacks you. You  \\##' '###\\######\\\\  \\)(/  //######/###' '##/\n"
    ++ "try to evade her attack by         )'    ''#)'  '##\\'->oo<-'/##'  '(#''    '(\n"
    ++ "jumping to the side.                       (       ''\\'..'/''       )\n"
    ++ "                                                      \\\"\"(\n"
    ++ "Successfully avoiding her claws and teeth you          '- )\n"
    ++ "quickly realise that the F.T.S. packed more than a     / /\n"
    ++ "dozent of snakemoths in here. Accepting your fate     ( /\\\n"
    ++ "you sit down and close your eyes before screaming     /\\| \\\n"
    ++ "up one last time!                                    (  \\\n"
    ++ "                                                         )\n"
    ++ "        ________                          ________      /             \n"
    ++ "       /  _____/_____    _____   ____     \\_____  \\___ (__ ___________ \n"
    ++ "      /   \\  ___\\__  \\  /     \\_/ __ \\     /   |   \\  \\/ // __ \\_  __ \\\n"
    ++ "      \\    \\_\\  \\/ __ \\|  Y Y  \\  ___/    /    |    \\   /\\  ___/|  | \\/\n"
    ++ "       \\______  (____  /__|_|  /\\___  >   \\_______  /\\_/  \\___  >__|   \n"
    ++ "              \\/     \\/      \\/     \\/            \\/          \\/    \n"

gameOverMonster = "\n"
    ++ "Quickly you turn around and try to run away but the monster    /\\ _ /\\\n"
    ++ "immediatly starts flying after you. After chasing you      /\\  | 6 6 |  /\\  \n"
    ++ "it bites you in the leg. You fall to the ground before    /  \\ \\ <\"> / /  \\\n"
    ++ "your face hits the rough dirt underneath you.            / ,__'~) - (~___, \\\n"
    ++ "You roll over just to see the big teeth of the          /.' ,-'`/_ /`'-,  '.\\\n"
    ++ "                    monster comming closer and biting     ,'    \\ _\\    ',\n"
    ++ "         /\\ _ /\\       eye out. You shriek out and try    :      \\ _\\     ;\n"
    ++ "     /\\  | 6 6 |  /\\       to push the monster to the     ',     / |/    ,'\n"
    ++ "    /  \\ \\ <\"> / /  \\     side with your hand.              '-,__\\ W\\_,-'\n"
    ++ "   / ,__'~) - (~___, \\     You succeed with pushing it away       ))\n"
    ++ "  /.' ,-'`/_ /`'-,  '.\\    before realising that you attracted    (\n"
    ++ "    ,'    \\ _\\    ',     another monster with your shriek.\n"
    ++ "    :      \\ _\\     ;   Accepting your fade you sit down and close your eyes.\n"
    ++ ".___',  .__/_|/  ._,'__.___ ._______     ._______  .___     ._______.______  \n"
    ++ ":_ ___\\-:      \\ :         |: .____/     : .___  \\ |   |___ : .____/: __   \\ \n"
    ++ "|   |___|   .   ||   \\  /  || : _/\\      | :   |  ||   |   || : _/\\ |  \\____|\n"
    ++ "|   /  ||   :   ||   |\\/   ||   /  \\     |     :  ||   :   ||   /  \\|   :  \\ \n"
    ++ "|. __  ||___|   ||___| |   ||_.: __/      \\_. ___/  \\      ||_.: __/|   |___\\\n"
    ++ " :/ |. |    |___|      |___|   :/           :/       \\____/    :/   |___|    \n"
    ++ " :   :/                                     :                                \n"
    ++ "     :\n"

showFigthScene (php, pmaxhp) (mhp, mmaxhp) atks strength msg spaces watered sliced input = ""
    ++ "                                                                               \n"
    ++ "---------------------------.                                  " ++ (if watered then "** Watered **" else "             ") ++ "    \n"
    ++ "  Monster:    Strength:   /                      " ++ spaces ++ "/\\ _ /\\\n"
    ++ "  " ++ (if spaces == "    " then "##" else "  ") ++ " " ++ (if mhp < 10 && mhp > -1 then " " ++ (show mhp) else show mhp) ++ "/" ++ (show mmaxhp) ++ " " ++ (if spaces == "    " then "##" else "  ") ++ "      " ++ (if strength < 10 then " " ++ (show strength) else show strength) ++ "    /                   " ++ spaces ++ "/\\  | " ++ (if mhp < 1 then "x x" else "6 6") ++ " |  /\\  " ++ (if sliced then "** Sliced **" else "             ") ++ "\n"
    ++ "------------------------'                   " ++ spaces ++ "/  \\ \\ <\"> / /  \\\n"
    ++ "                                           " ++ spaces ++ "/ ,__'~) - (~___, \\\n"
    ++ "                                          " ++ spaces ++ "/.' ,-'`/_ /`'-,  '.\\\n"
    ++ "     [1] " ++ (if elem "1" atks then "Basic Knife Attack" else "-                 ") ++ "                 " ++ spaces ++ ",'    \\ _\\    ',\n"
    ++ "           " ++ (if elem "1" atks then "Damage: 5, Accuracy: 95%" else "                        ") ++ "         " ++ spaces ++ ":      \\ _\\     ;\n"
    ++ "                                            " ++ spaces ++ "',     / |/    ,'\n"
    ++ "     [2] " ++ (if elem "2" atks then "Plasma Sword Attack" else "-                  ") ++ "                  " ++ spaces ++ "'-,__\\ W\\_,-'\n"
    ++ "           " ++ (if elem "2" atks then "Damage: 9, Accuracy: 75%" else "                        ") ++ "                 " ++ spaces ++ "((\n"
    ++ "                                                     " ++ spaces ++ ")\n"
    ++ "     [3] " ++ (if elem "3" atks then "Stun Gun Attack" else "-              ") ++ "                                                       \n"
    ++ "           " ++ (if elem "3" atks then "Damage: 3, Accuracy: 90%" else "                        ") ++ "                                            \n"
    ++ "                                                        .----------------------\n"
    ++ "     [4] " ++ (if elem "4" atks then "Air Condensator" else "-              ") ++ "                                 \\     You:            \n"
    ++ "           " ++ (if elem "4" atks then "Reduction: 1, Accuracy: 100%" else "                            ") ++ "                   \\    " ++ (if spaces == "" then "##" else "  ") ++ " " ++ (if php < 10 then " " ++ (show php) else show php) ++ "/" ++ (show pmaxhp) ++ " " ++ (if spaces == "" then "##" else "  ") ++ "     \n"
    ++ "                                                           '-------------------\n"
    ++ "     [5] Run away                                                              \n"
    ++ "\n"
    ++ "                            " ++ msg ++ "\n"
    ++ "                                                                               \n"
    ++ "" ++ (if input then ">> " else "                                                                               ") ++ ""

enteringCave = "Without fear you venture off into the depths of the cave.\n"
    ++ "After turning left and now facing north you have gotten yourself into a"
    ++ "room-ish like cavern with three branches."

foundDeadBody = "On the ground you find one seperated arm. Your feeling tells you that you are\n"
    ++ "not alone here and that you should go back the ship immediately. But first you\n"
    ++ "inspect the arm. Due to the small tattoos on the hand you quickly realise that\n"
    ++ "this is the arm of your former engineering supervisor Alan Rickman.\n"
    ++ "Upon closer inspection you see the code \"4546B\" written on it."

analyseFragment = "For time reasons the developer had no possibility to add a text here. I apologize for the inconvenience."

locName r
    | r ==  1 = "Level 0 - Floor"
    | r ==  2 = "Level 0 - Elevator Room"
    | r ==  3 = "Level 0 - Chiefs Room"
    | r ==  4 = "Level 0 - Machine Room"
    | r ==  5 = "Level 0 - Snake Farm"
    | r ==  6 = "Level 0 - Terminal Room"
    | r ==  7 = "Level 0 - Laboratory"
    | r ==  8 = "Level 0 - Western Panorama Room"
    | r ==  9 = "Level 0 - Preperation Room"
    | r == 10 = "Level 0 - Airlock Room"
    | r == 11 = "Level 1 - Elevator Room"
    | r == 12 = "Level 1 - Eastern Panorama Room"
    | r == 13 = "Level 1 - Northern Floor"
    | r == 14 = "Level 1 - Southern Floor"
    | r == 15 = "Level 1 - Incubation Room"
    | r == 16 = "Level 1 - Stock"
    | r == 17 = "Level 1 - Eastern Floor"
    | r == 18 = "Level 2 - Elevator Room"
    | r == 19 = "Level 2 - Transmission Room"
    | r == 20 = "Cave"
    | r == 21 = "Level 01 - Elevator Room"
    | r == 22 = "Level 01 - Prison"
    | r == 23 = "Level 01 - Southern Floor"
    | r == 24 = "Level 01 - Northern Floor"
    | r == 25 = "Level 01 - Captains Room"
    | otherwise = "Error"

locText r
    | r ==  1 = "You are in a rectangular room with doors on each of the four walls. Every door\nhas a sign next to it. The northern door says 'Elevators', the eastern door\nsays 'Machine room', the southern door says 'Terminal room' and the western\ndoor says 'Panorama room'."
    | r ==  2 = "You are in a room with three doors and an elevator that can take you up and down\na floor. The sign on the eastern door says 'Security Chief Chirpas room'.\nThe door to the south gets you to 'Floor 0' while the door to the west gets\nyou to the 'Laboratory'."
    | r ==  3 = "You are in the bedroom of security chief Chirpa. From the ceiling comes light\nthrough the hole. The only way to get out of this room is to use the door to\nthe west. It says 'Elevators'."
    | r ==  4 = "How did you get in here? This room is not implemented yet!"
    | r ==  5 = "This message should not show up. If it does, please ignore!"
    | r ==  6 = "You are in the terminal room. To the north is a door with the sign 'Floor 0'.\nTo the east there is a door with the sign 'Snakemoth Farm' but its blocked\nby scrap metal. To the west there is a door that will take you to the\n'Preperation room'. Right in front of you is a Linux terminal."
    | r ==  7 = "You are in the science lab. Both the fabricator and incubation device are\ndestroyed but the fabricator still seems usable. You can use the door to your\neast to go to the 'Elevators'. The door to the south will take you to\nthe 'Panorama room'."
    | r ==  8 = "You are in the western panorama room. To the west you can see through the\ngiant window into the unknown depths of the galaxy.\nThere are three doors with signs next to them in here. The northern door\nsays 'Laboratory', the eastern door says 'Floor 0' and\nthe southern door says 'Preperation room'."
    | r ==  9 = "You are in the airlock preperation room. Sadly, the airlock has been\ndemolished. But you can go to the north to enter 'Panorama room' and to\nthe east to enter 'Terminal room'."
    | r == 10 = "This room does not exist."
    | r == 11 = "You are in the elevator room on floor 1. The elevator can take you to level\n0 and 2. There are two doors in here. The signs on the doors say\n'Panorama room' for the eastern door and 'Floor 1 - Northern Floor'\nfor the southern door."
    | r == 12 = "You are in the eastern panorama room. The big panorama window is blocked by\nsomething that looks like a meteor stone wall. There is a shelf in\nthe middle of the room that appears to have been fallen down. The only way\nout is a door on the west that takes you back to the 'Elevators'."
    | r == 13 = "You are in the northern floor of level 1. There is nothing to see here but\nthe northern door taking you to the 'Elevators' and the southern door that\ntakes you to 'Floor 1 - Southern Floor'."
    | r == 14 = "You are in the southern floor of level 1. There is nothing to see here but\nthe northern door taking you to 'Floor 1 - Northern Floor', the eastern door\nthat takes you to 'Floor 1 - Eastern Floor' and the western door that takes\nyou to the 'Stock room'."
    | r == 15 = "This room does not exist."
    | r == 16 = "You are in the stock of this ship. There are four lockers in this room, each\nwith a security code. The only way out is to go where you came from."
    | r == 17 = "You are in the eastern floor of level 1. The western wall contains a door\ntaking you back to 'Floor 1 - Southern Floor'. On the eastern side there\nis a huge hole in the ships hull. Apparently the ship has crashed into the rock\nformation with such fast speeds that it melted together with the asteroid to\ncapture the fresh air inside and don't letting it out. Looking further you see\nthat the asteroid actually has a cave entrance."
    | r == 18 = "You are in the elevator room on floor 2. There is only one door to the south\ntaking you to the 'Transmission room' and the elevator that can only take\nyou down."
    | r == 19 = "You are in the transmission room. In front of you is a huge transmission tower.\nBefore it can send any help signals you have to put a long field communication\ndevice into the tower."
    | r == 20 = "Cave"
    | r == 21 = "You are in the Elevator Room of level 01. There is a door to the east with the\nsign 'Floor 01 - Southern Floor' next to it and one to the west with the sign\n'Prison' next to it."
    | r == 22 = "You are in the prison room of the F.T.S. Discovery. Behing the security glass\nlies the dead body of an inprissioned Navanian. There is also a ship fragment\non the ground with the note 'TO BE ANALYSED' sticked to it. The only way\nout of this room is to the east because the other doors are blocked."
    | r == 23 = "You are on the southern floor. There is nothing to see here but two doors. The\ndoor to the north takes you 130m to the northern floor with a horizontal\nelevator. The door to the west takes you to the Elevator Room."
    | r == 24 = "You are on the northern floor. With the exception of the eastern door taking\nyou to the captains room and the southern door taking you 130m to the southern\nfloor there is nothing to see."
    | r == 25 = "You find youself in the captains quarters. Her dead body lies on the ground. Your only way out is the door to the west."
    | otherwise = "Error"

itemName i
    | i ==  0 = "Chiefs ID"
    | i ==  1 = "Long Field Communication Module (LFCM)"
    | i ==  2 = "Universal Compression Unit (UCU)"
    | i ==  3 = "Voice Message"
    | i ==  4 = "combat knife"
    | i ==  5 = "plasma sword"
    | i ==  6 = "stun gun"
    | i ==  7 = "air condensator"
    | i ==  8 = "analysis ball"
    | i ==  9 = "scrap metal"
    | i == 10 = "Captains ID"
    | i == 11 = "Palaks ID"
    | i == 12 = "MediKit"
    | otherwise = "Error"

itemText i
    | i ==  0 = "This is the identification card of the security chief Jay C. Chirpa. The data\non this card is corrupted but it still allows you to access rooms with a\nhigher security level."
    | i ==  1 = "The standard long field mommunication module allows devices to create\nhyperdimensional intersection to send information at huge speeds."
    | i ==  2 = "The universal compression unit is used as a repair part for certain\ndevices."
    | i ==  3 = "There are two messages:\nMessage one: \"Hey there. Here is Alan .. Alan Rickman, your former engineering\n supervisor .. I found your seemingly lifeless body after the accident that\n caused us to jump to the wrong location.\n The ship seems to have colided with something huge. As far as\n I know everybody else on this ship is dead .. we are the last\n survivors .. I will do my best to keep you alive and safe so let's hope for the best!\"\n*Message ended*\n\nMessage two: \"OK .. you have been asleep for the last two hours and\n unfortunately there is a problem with the transmission tower and I don't have\n the neccessary parts. So I can't send help. I've seen something on the eastern\n floor that can maybe help us so I think I will go out and look that up but\n I'll be back as fast as I can.\"\n*Message ended*"
    | i ==  4 = "It is just a basic combat knife."
    | i ==  5 = "With this sword you have access to great damage but with less\naccuracy."
    | i ==  6 = "This stun gun shoots small electronic bullets. Warning: Don't use on targets with open wounds or liquids on them!"
    | i ==  7 = "This device allows you to condensate the water in the air\narround you to then shoot it in the direction you want."
    | i ==  8 = "If you put this small ball in an object it will automatically\nscan its surrounding to analyse its parts."
    | i ==  9 = "Scrap metal is used for many recipes in the fabricator."
    | i == 10 = "The data on this identification card reveals some information about the\ncaptain. Her full name is Lila Celine Marek and she is the vice president of the\nFederation of Terran Systems."
    | i == 11 = "The data on this identification card reveals some information about Palak\nAlviin. He is the second president of the Alviin Septem family, seventh seat on\nthe Council of the Novan Family Clans."
    | i == 12 = "This MediKit will help you regain HP.\nUsage: Type MediKit"
    | otherwise = "Error"
